apiVersion: v1
kind: Secret
metadata:
  name: gitops-demo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:pentago/gitops-demo-config.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDF/KMCeCYR1aAWeLjYjoQfqUjZxfk4RedOKKr+b5jfNQAAAKAzMW8gMzFv
    IAAAAAtzc2gtZWQyNTUxOQAAACDF/KMCeCYR1aAWeLjYjoQfqUjZxfk4RedOKKr+b5jfNQ
    AAAEAMXoeirjOh06zXBn244BbE1ylaxLh4j4wXpI77UzojlMX8owJ4JhHVoBZ4uNiOhB+p
    SNnF+ThF504oqv5vmN81AAAAF0dpdE9wcyBEZW1vIENvbmZpZyBSZXBvAQIDBAUG
    -----END OPENSSH PRIVATE KEY-----
