apiVersion: v1
kind: Secret
metadata:
  name: gitops-demo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  name: gitops-demo-config
  url: https://github.com/pentago/gitops-demo-config.git
